In [1]:
import numpy as np

# Step 1: Define states and observations based on user input
states = list(map(str.strip, input("Enter the states (comma-separated): ").split(',')))
observations = list(map(str.strip, input("Enter the possible observations (comma-separated): ").split(',')))

# Step 2: Get user input for the observation sequence
observation_seq = list(map(str.strip, input(f"Enter the observation sequence as space-separated names (options: {observations}): ").split()))

# Step 3: Convert observation sequence to indices
try:
    observation_indices = [observations.index(obs) for obs in observation_seq]
except ValueError as e:
    print(f"Error: {e}. Please make sure your observation sequence contains only valid options: {observations}.")
    exit()

# Step 4: Get user input for the transition matrix
print("\nEnter the state transition probabilities:")
transition_matrix = np.zeros((len(states), len(states)))
for i in range(len(states)):
    for j in range(len(states)):
        transition_matrix[i, j] = float(input(f"P({states[j]} | {states[i]}): "))

# Step 5: Get user input for the emission matrix
print("\nEnter the emission probabilities:")
emission_matrix = np.zeros((len(states), len(observations)))
for i in range(len(states)):
    for j in range(len(observations)):
        emission_matrix[i, j] = float(input(f"P({observations[j]} | {states[i]}): "))

# Step 6: Set initial state probabilities (ask the user to input them)
initial_probabilities = np.zeros(len(states))
print("\nEnter the initial state probabilities (comma-separated):")
initial_probabilities = list(map(float, input(f"Enter initial probabilities for {states}: ").split(',')))

# Step 7: Backward Procedure
def backward_procedure(observation_seq, transition_matrix, emission_matrix):
    num_states = len(transition_matrix)
    num_observations = len(observation_seq)
    
    # Initialize the backward matrix
    backward_matrix = np.zeros((num_states, num_observations))
    
    # Initialization step: Fill the last column with 1 (termination condition)
    backward_matrix[:, num_observations - 1] = 1
    
    # Recursion step
    for t in range(num_observations - 2, -1, -1):
        for i in range(num_states):
            backward_matrix[i, t] = sum(transition_matrix[i, j] * emission_matrix[j, observation_seq[t + 1]] * backward_matrix[j, t + 1] for j in range(num_states))
    
    # Compute the probability of the observation sequence
    prob_observation = sum(initial_probabilities[i] * emission_matrix[i, observation_seq[0]] * backward_matrix[i, 0] for i in range(num_states))
    
    return backward_matrix, prob_observation

# Step 8: Viterbi Algorithm (to find the best state sequence)
def viterbi_algorithm(observation_seq, transition_matrix, emission_matrix, initial_probabilities):
    num_states = len(transition_matrix)
    num_observations = len(observation_seq)
    
    # Initialize the Viterbi matrix and the backpointer matrix
    viterbi_matrix = np.zeros((num_states, num_observations))
    backpointer = np.zeros((num_states, num_observations), dtype=int)
    
    # Initialization step
    for i in range(num_states):
        viterbi_matrix[i, 0] = initial_probabilities[i] * emission_matrix[i, observation_seq[0]]
    
    # Recursion step
    for t in range(1, num_observations):
        for j in range(num_states):
            probabilities = [viterbi_matrix[i, t - 1] * transition_matrix[i, j] * emission_matrix[j, observation_seq[t]] for i in range(num_states)]
            viterbi_matrix[j, t] = max(probabilities)
            backpointer[j, t] = np.argmax(probabilities)
    
    # Termination step
    best_last_state = np.argmax(viterbi_matrix[:, num_observations - 1])
    
    # Backtrack to find the most probable state sequence
    best_path = [best_last_state]
    for t in range(num_observations - 1, 0, -1):
        best_last_state = backpointer[best_last_state, t]
        best_path.insert(0, best_last_state)
    
    best_state_sequence = [states[state_index] for state_index in best_path]
    
    return best_state_sequence, viterbi_matrix

# Step 9: Compute the backward matrix and the probability of the observation sequence
backward_matrix, prob_observation_backward = backward_procedure(observation_indices, transition_matrix, emission_matrix)
print("\nBackward Matrix:\n", backward_matrix)
print("Probability of the observation sequence (using backward procedure):", prob_observation_backward)

# Step 10: Compute the most probable state sequence using Viterbi algorithm
best_state_sequence, viterbi_matrix = viterbi_algorithm(observation_indices, transition_matrix, emission_matrix, initial_probabilities)
print("\nViterbi Matrix:\n", viterbi_matrix)
print("Most probable state sequence:", best_state_sequence)


Enter the states (comma-separated):  cp,ip
Enter the possible observations (comma-separated):  lem,icet,cola
Enter the observation sequence as space-separated names (options: ['lem', 'icet', 'cola']):  lem icet cola



Enter the state transition probabilities:


P(cp | cp):  0.7
P(ip | cp):  0.5
P(cp | ip):  0.3
P(ip | ip):  0.5



Enter the emission probabilities:


P(lem | cp):  0.3
P(icet | cp):  0.1
P(cola | cp):  0.6
P(lem | ip):  0.2
P(icet | ip):  0.7
P(cola | ip):  0.1



Enter the initial state probabilities (comma-separated):


Enter initial probabilities for ['cp', 'ip']:  1.0,0.0



Backward Matrix:
 [[0.1134 0.47   1.    ]
 [0.0946 0.23   1.    ]]
Probability of the observation sequence (using backward procedure): 0.03401999999999999

Viterbi Matrix:
 [[0.3     0.021   0.0189 ]
 [0.      0.105   0.00525]]
Most probable state sequence: ['cp', 'ip', 'cp']


In [1]:
import numpy as np

# Step 1: Define states and observations based on user input
states = list(map(str.strip, input("Enter the states (comma-separated): ").split(',')))
observations = list(map(str.strip, input("Enter the possible observations (comma-separated): ").split(',')))

# Step 2: Get user input for the observation sequence
observation_seq = list(map(str.strip, input(f"Enter the observation sequence as space-separated names (options: {observations}): ").split()))

# Step 3: Convert observation sequence to indices
try:
    observation_indices = [observations.index(obs) for obs in observation_seq]
except ValueError as e:
    print(f"Error: {e}. Please make sure your observation sequence contains only valid options: {observations}.")
    exit()

# Step 4: Get user input for the transition matrix
print("\nEnter the state transition probabilities:")
transition_matrix = np.zeros((len(states), len(states)))
for i in range(len(states)):
    for j in range(len(states)):
        transition_matrix[i, j] = float(input(f"P({states[j]} | {states[i]}): "))

# Step 5: Get user input for the emission matrix
print("\nEnter the emission probabilities:")
emission_matrix = np.zeros((len(states), len(observations)))
for i in range(len(states)):
    for j in range(len(observations)):
        emission_matrix[i, j] = float(input(f"P({observations[j]} | {states[i]}): "))

# Step 6: Set initial state probabilities (ask the user to input them)
initial_probabilities = np.zeros(len(states))
print("\nEnter the initial state probabilities (comma-separated):")
initial_probabilities = list(map(float, input(f"Enter initial probabilities for {states}: ").split(',')))

# Step 7: Backward Procedure
def backward_procedure(observation_seq, transition_matrix, emission_matrix):
    num_states = len(transition_matrix)
    num_observations = len(observation_seq)
    
    # Initialize the backward matrix
    backward_matrix = np.zeros((num_states, num_observations))
    
    # Initialization step: Fill the last column with 1 (termination condition)
    backward_matrix[:, num_observations - 1] = 1
    
    # Recursion step
    for t in range(num_observations - 2, -1, -1):
        for i in range(num_states):
            backward_matrix[i, t] = sum(transition_matrix[i, j] * emission_matrix[j, observation_seq[t + 1]] * backward_matrix[j, t + 1] for j in range(num_states))
    
    # Compute the probability of the observation sequence
    prob_observation = sum(initial_probabilities[i] * emission_matrix[i, observation_seq[0]] * backward_matrix[i, 0] for i in range(num_states))
    
    return backward_matrix, prob_observation

# Step 8: Viterbi Algorithm (to find the best state sequence)
def viterbi_algorithm(observation_seq, transition_matrix, emission_matrix, initial_probabilities):
    num_states = len(transition_matrix)
    num_observations = len(observation_seq)
    
    # Initialize the Viterbi matrix and the backpointer matrix
    viterbi_matrix = np.zeros((num_states, num_observations))
    backpointer = np.zeros((num_states, num_observations), dtype=int)
    
    # Initialization step
    for i in range(num_states):
        viterbi_matrix[i, 0] = initial_probabilities[i] * emission_matrix[i, observation_seq[0]]
    
    # Recursion step
    for t in range(1, num_observations):
        for j in range(num_states):
            probabilities = [viterbi_matrix[i, t - 1] * transition_matrix[i, j] * emission_matrix[j, observation_seq[t]] for i in range(num_states)]
            viterbi_matrix[j, t] = max(probabilities)
            backpointer[j, t] = np.argmax(probabilities)
    
    # Termination step
    best_last_state = np.argmax(viterbi_matrix[:, num_observations - 1])
    
    # Backtrack to find the most probable state sequence
    best_path = [best_last_state]
    for t in range(num_observations - 1, 0, -1):
        best_last_state = backpointer[best_last_state, t]
        best_path.insert(0, best_last_state)
    
    best_state_sequence = [states[state_index] for state_index in best_path]
    
    return best_state_sequence, viterbi_matrix

# Step 9: Compute the backward matrix and the probability of the observation sequence
backward_matrix, prob_observation_backward = backward_procedure(observation_indices, transition_matrix, emission_matrix)
print("\nBackward Matrix:\n", backward_matrix)
print("Probability of the observation sequence (using backward procedure):", prob_observation_backward)

# Step 10: Compute the most probable state sequence using Viterbi algorithm
best_state_sequence, viterbi_matrix = viterbi_algorithm(observation_indices, transition_matrix, emission_matrix, initial_probabilities)
print("\nViterbi Matrix:\n", viterbi_matrix)
print("Most probable state sequence:", best_state_sequence)


Enter the states (comma-separated):  1,2,3
Enter the possible observations (comma-separated):  up,down,unchanged
Enter the observation sequence as space-separated names (options: ['up', 'down', 'unchanged']):  up up up up up



Enter the state transition probabilities:


P(1 | 1):  0.6
P(2 | 1):  0.2
P(3 | 1):  0.2
P(1 | 2):  0.5
P(2 | 2):  0.3
P(3 | 2):  0.2
P(1 | 3):  0.4
P(2 | 3):  0.1
P(3 | 3):  0.5



Enter the emission probabilities:


P(up | 1):  0.7
P(down | 1):  0.1
P(unchanged | 1):  0.2
P(up | 2):  0.1
P(down | 2):  0.6
P(unchanged | 2):  0.3
P(up | 3):  0.3
P(down | 3):  0.3
P(unchanged | 3):  0.4



Enter the initial state probabilities (comma-separated):


Enter initial probabilities for ['1', '2', '3']:  0.5,0.2,0.3



Backward Matrix:
 [[0.05859736 0.1199     0.2452     0.5        1.        ]
 [0.05125318 0.104882   0.2146     0.44       1.        ]
 [0.04997512 0.102362   0.2104     0.44       1.        ]]
Probability of the observation sequence (using backward procedure): 0.026031900399999995

Viterbi Matrix:
 [[0.35       0.147      0.06174    0.0259308  0.01089094]
 [0.02       0.007      0.00294    0.0012348  0.00051862]
 [0.09       0.021      0.00882    0.0037044  0.00155585]]
Most probable state sequence: ['1', '1', '1', '1', '1']


In [2]:
import numpy as np
class HiddenMarkovModel:
    def __init__(self, states, observations, start_prob, trans_prob, emission_prob):
        self.states = states  # Possible hidden states (tags)
        self.observations = observations  # Possible observations (words)
        self.start_prob = start_prob  # Initial probabilities of states
        self.trans_prob = trans_prob  # Transition probabilities between states
        self.emission_prob = emission_prob  # Emission probabilities of states producing observations

    def viterbi(self, obs_seq):
        n_states = len(self.states)
        n_observations = len(obs_seq)

        viterbi_table = np.zeros((n_states, n_observations))
        backpointer = np.zeros((n_states, n_observations), dtype=int)

        for s in range(n_states):
            viterbi_table[s, 0] = self.start_prob[s] * self.emission_prob[s][self.observations.index(obs_seq[0])]
            backpointer[s, 0] = 0

        for t in range(1, n_observations):
            for s in range(n_states):

                max_prob, max_state = max(
                    (viterbi_table[prev_s, t-1] * self.trans_prob[prev_s][s] *
                     self.emission_prob[s][self.observations.index(obs_seq[t])], prev_s)
                    for prev_s in range(n_states)
                )
                viterbi_table[s, t] = max_prob
                backpointer[s, t] = max_state
        
        best_path_prob = max(viterbi_table[:, -1])
        best_path_pointer = np.argmax(viterbi_table[:, -1])
        best_path = [best_path_pointer]
        
        for t in range(n_observations - 1, 0, -1):
            best_path_pointer = backpointer[best_path_pointer, t]
            best_path.insert(0, best_path_pointer)
        
        best_state_sequence = [self.states[i] for i in best_path]
        return best_state_sequence, best_path_prob


def get_user_input():
    num_states = int(input("Enter the number of states: "))
    states = []
    for i in range(num_states):
        state = input(f"Enter state {i + 1}: ")
        states.append(state)
    
    num_observations = int(input("Enter the number of observations: "))
    observations = []
    for i in range(num_observations):
        observation = input(f"Enter observation {i + 1}: ")
        observations.append(observation)
    
    print("\nEnter start probabilities for each state:")
    start_prob = []
    for state in states:
        prob = float(input(f"Start probability for {state}: "))
        start_prob.append(prob)
    
    print("\nEnter transition probabilities (from each state to other states):")
    trans_prob = []
    for i, from_state in enumerate(states):
        trans_row = []
        for j, to_state in enumerate(states):
            prob = float(input(f"Transition probability from {from_state} to {to_state}: "))
            trans_row.append(prob)
        trans_prob.append(trans_row)
    
    print("\nEnter emission probabilities (from each state to each observation):")
    emission_prob = []
    for i, state in enumerate(states):
        emission_row = []
        for j, observation in enumerate(observations):
            prob = float(input(f"Emission probability of {observation} from {state}: "))
            emission_row.append(prob)
        emission_prob.append(emission_row)
    
    return states, observations, start_prob, trans_prob, emission_prob


if __name__ == "__main__":
    states, observations, start_prob, trans_prob, emission_prob = get_user_input()

    hmm = HiddenMarkovModel(states, observations, start_prob, trans_prob, emission_prob)

    obs_seq = input("\nEnter the observation sequence (space-separated): ").split()

    best_sequence, best_prob = hmm.viterbi(obs_seq)
    print("\nBest state sequence:", best_sequence)
    print("Best path probability:", best_prob)
    

Enter the number of states:  2
Enter state 1:  cp
Enter state 2:  ip
Enter the number of observations:  3
Enter observation 1:  lem
Enter observation 2:  icet
Enter observation 3:  cola



Enter start probabilities for each state:


Start probability for cp:  1.0
Start probability for ip:  0.0



Enter transition probabilities (from each state to other states):


Transition probability from cp to cp:  0.7
Transition probability from cp to ip:  0.3
Transition probability from ip to cp:  0.5
Transition probability from ip to ip:  0.5



Enter emission probabilities (from each state to each observation):


Emission probability of lem from cp:  0.3
Emission probability of icet from cp:  0.1
Emission probability of cola from cp:  0.6
Emission probability of lem from ip:  0.2
Emission probability of icet from ip:  0.7
Emission probability of cola from ip:  0.1

Enter the observation sequence (space-separated):  lem icet cola



Best state sequence: ['cp', 'ip', 'cp']
Best path probability: 0.0189
