In [1]:
import numpy as np

# Step 1: Define states and observations based on user input
states = list(map(str.strip, input("Enter the states (comma-separated): ").split(',')))
observations = list(map(str.strip, input("Enter the possible observations (comma-separated): ").split(',')))

# Step 2: Get user input for the observation sequence
observation_seq = list(map(str.strip, input(f"Enter the observation sequence as space-separated names (options: {observations}): ").split()))

# Step 3: Convert observation sequence to indices
try:
    observation_indices = [observations.index(obs) for obs in observation_seq]
except ValueError as e:
    print(f"Error: {e}. Please make sure your observation sequence contains only valid options: {observations}.")
    exit()

# Step 4: Get user input for the transition matrix
print("\nEnter the state transition probabilities:")
transition_matrix = np.zeros((len(states), len(states)))
for i in range(len(states)):
    for j in range(len(states)):
        transition_matrix[i, j] = float(input(f"P({states[j]} | {states[i]}): "))

# Step 5: Get user input for the emission matrix
print("\nEnter the emission probabilities:")
emission_matrix = np.zeros((len(states), len(observations)))
for i in range(len(states)):
    for j in range(len(observations)):
        emission_matrix[i, j] = float(input(f"P({observations[j]} | {states[i]}): "))

# Step 6: Set initial state probabilities (ask the user to input them)
initial_probabilities = np.zeros(len(states))
print("\nEnter the initial state probabilities (comma-separated):")
initial_probabilities = list(map(float, input(f"Enter initial probabilities for {states}: ").split(',')))

# Step 7: Forward Procedure
def forward_procedure(observation_seq, transition_matrix, emission_matrix, initial_probabilities):
    num_states = len(transition_matrix)
    num_observations = len(observation_seq)
    
    # Initialize the forward matrix
    forward_matrix = np.zeros((num_states, num_observations))
    
    # Initialization step
    for i in range(num_states):
        forward_matrix[i, 0] = initial_probabilities[i] * emission_matrix[i, observation_seq[0]]
    
    # Recursion step
    for t in range(1, num_observations):
        for j in range(num_states):
            forward_matrix[j, t] = sum(forward_matrix[i, t - 1] * transition_matrix[i, j] for i in range(num_states)) * emission_matrix[j, observation_seq[t]]
    
    # Termination step
    prob_observation = sum(forward_matrix[i, num_observations - 1] for i in range(num_states))
    
    return forward_matrix, prob_observation

# Step 8: Compute the forward matrix and the probability of the observation sequence
forward_matrix, prob_observation = forward_procedure(observation_indices, transition_matrix, emission_matrix, initial_probabilities)

# Display the results
print("\nForward Matrix:\n", forward_matrix)
print("Probability of the observation sequence:", prob_observation)

Enter the states (comma-separated):  cp,ip
Enter the possible observations (comma-separated):  lem,icet,cola
Enter the observation sequence as space-separated names (options: ['lem', 'icet', 'cola']):  lem icet cola



Enter the state transition probabilities:


P(cp | cp):  0.7
P(ip | cp):  0.5
P(cp | ip):  0.3
P(ip | ip):  0.5



Enter the emission probabilities:


P(lem | cp):  0.3
P(icet | cp):  0.1
P(cola | cp):  0.6
P(lem | ip):  0.2
P(icet | ip):  0.7
P(cola | ip):  0.1



Enter the initial state probabilities (comma-separated):


Enter initial probabilities for ['cp', 'ip']:  1.0,0.0



Forward Matrix:
 [[0.3     0.021   0.02772]
 [0.      0.105   0.0063 ]]
Probability of the observation sequence: 0.034019999999999995


In [2]:
import numpy as np

# Step 1: Define states and observations based on user input
states = list(map(str.strip, input("Enter the states (comma-separated): ").split(',')))
observations = list(map(str.strip, input("Enter the possible observations (comma-separated): ").split(',')))

# Step 2: Get user input for the observation sequence
observation_seq = list(map(str.strip, input(f"Enter the observation sequence as space-separated names (options: {observations}): ").split()))

# Step 3: Convert observation sequence to indices
try:
    observation_indices = [observations.index(obs) for obs in observation_seq]
except ValueError as e:
    print(f"Error: {e}. Please make sure your observation sequence contains only valid options: {observations}.")
    exit()

# Step 4: Get user input for the transition matrix
print("\nEnter the state transition probabilities:")
transition_matrix = np.zeros((len(states), len(states)))
for i in range(len(states)):
    for j in range(len(states)):
        transition_matrix[i, j] = float(input(f"P({states[j]} | {states[i]}): "))

# Step 5: Get user input for the emission matrix
print("\nEnter the emission probabilities:")
emission_matrix = np.zeros((len(states), len(observations)))
for i in range(len(states)):
    for j in range(len(observations)):
        emission_matrix[i, j] = float(input(f"P({observations[j]} | {states[i]}): "))

# Step 6: Set initial state probabilities (ask the user to input them)
initial_probabilities = np.zeros(len(states))
print("\nEnter the initial state probabilities (comma-separated):")
initial_probabilities = list(map(float, input(f"Enter initial probabilities for {states}: ").split(',')))

# Step 7: Forward Procedure
def forward_procedure(observation_seq, transition_matrix, emission_matrix, initial_probabilities):
    num_states = len(transition_matrix)
    num_observations = len(observation_seq)
    
    # Initialize the forward matrix
    forward_matrix = np.zeros((num_states, num_observations))
    
    # Initialization step
    for i in range(num_states):
        forward_matrix[i, 0] = initial_probabilities[i] * emission_matrix[i, observation_seq[0]]
    
    # Recursion step
    for t in range(1, num_observations):
        for j in range(num_states):
            forward_matrix[j, t] = sum(forward_matrix[i, t - 1] * transition_matrix[i, j] for i in range(num_states)) * emission_matrix[j, observation_seq[t]]
    
    # Termination step
    prob_observation = sum(forward_matrix[i, num_observations - 1] for i in range(num_states))
    
    return forward_matrix, prob_observation

# Step 8: Compute the forward matrix and the probability of the observation sequence
forward_matrix, prob_observation = forward_procedure(observation_indices, transition_matrix, emission_matrix, initial_probabilities)

# Display the results
print("\nForward Matrix:\n", forward_matrix)
print("Probability of the observation sequence:", prob_observation)

Enter the states (comma-separated):  1,2,3
Enter the possible observations (comma-separated):  up,down,unchanged
Enter the observation sequence as space-separated names (options: ['up', 'down', 'unchanged']):  up up up up up



Enter the state transition probabilities:


P(1 | 1):  0.6
P(2 | 1):  0.2
P(3 | 1):  0.2
P(1 | 2):  0.5
P(2 | 2):  0.3
P(3 | 2):  0.2
P(1 | 3):  0.4
P(2 | 3):  0.1
P(3 | 3):  0.5



Enter the emission probabilities:


P(up | 1):  0.7
P(down | 1):  0.1
P(unchanged | 1):  0.2
P(up | 2):  0.1
P(down | 2):  0.6
P(unchanged | 2):  0.3
P(up | 3):  0.3
P(down | 3):  0.3
P(unchanged | 3):  0.4



Enter the initial state probabilities (comma-separated):


Enter initial probabilities for ['1', '2', '3']:  0.5,0.2,0.3



Forward Matrix:
 [[0.35       0.1792     0.088235   0.04318006 0.02110624]
 [0.02       0.0085     0.004196   0.00205675 0.00100569]
 [0.09       0.0357     0.016617   0.00803841 0.00391997]]
Probability of the observation sequence: 0.026031900399999995


In [4]:
import numpy as np
states=list(map(str.strip,input("Enter the states(comma-separated):").split(',')))
observations=list(map(str.strip,input("Enter the possible observations(comma-separated):").split(',')))
observation_seq=list(map(str.strip,input(f"Enter the observation sequence as space_separated names(options:{observations}):").split()))
try:
    observation_indices=[]
    for obs in observation_seq:
        observation_indices.append(observations.index(obs))
except ValueError as e:
    print(f"Error:{e}.Please make sure your observation sequence contains only valid options:{observations}.")
    exit()
print("\nEnter the state transition probabilities:")
transition_matrix=np.zeros((len(states),len(states)))
for i in range(len(states)):
    for j in range(len(states)):
        transition_matrix[i,j]=float(input(f"P({states[j]}|{states[i]}):"))
print("\nEnter the emission probabilities:")
emission_matrix=np.zeros((len(states),len(observations)))
for i in range(len(states)):
    for j in range(len(observations)):
        emission_matrix[i,j]=float(input(f"P({observations[j]}|{states[i]}):"))
initial_probabilities=np.zeros(len(states))
print("\nEnter the initial state probabilities(comma-separated):")
initial_probabilities=list(map(float,input(f"Enter initial probabilities for{states}:").split(',')))

def forward_procedure(observation_seq,transition_matrix,emission_matrix,initial_probabilities):
    num_states=len(transition_matrix)
    num_observations=len(observation_seq)
    forward_matrix=np.zeros((num_states,num_observations))
    for i in range(num_states):
        forward_matrix[i, 0]=initial_probabilities[i] * emission_matrix[i, observation_seq[0]]
    for t in range(1,num_observations):
        for j in range(num_states):
            forward_matrix[j,t]=sum(forward_matrix[i,t-1]*transition_matrix[i,j] for i in range(num_states))*emission_matrix[j,observation_seq[t]]
    prob_observation=sum(forward_matrix[i,num_observations-1]for i in range(num_states))
    return forward_matrix,prob_observation

forward_matrix,prob_observation=forward_procedure(observation_indices,transition_matrix,emission_matrix,initial_probabilities)
print("\nForward Matrix:\n",forward_matrix)
print("Probability of observation sequence:",prob_observation)

def backward_procedure(observation_seq,transition_matrix,emission_matrix,initial_probabilities):
    num_states=len(transition_matrix)
    num_observations=len(observation_seq)
    backward_matrix=np.zeros((num_states,num_observations))
    backward_matrix[:,num_observations-1]=1
    for  t in range(num_observations-2,-1,-1):
        for i in range(num_states):
            backward_matrix[i,t]=sum(transition_matrix[i,j]*emission_matrix[j, observation_seq[t+1]]*backward_matrix[j,t+1]for j in range(num_states))
    prob_observation=sum(initial_probabilities[i]*emission_matrix[i, observation_seq[0]]*backward_matrix[i,0]for i in range(num_states))
    return backward_matrix,prob_observation

backward_matrix,prob_observation=backward_procedure(observation_indices,transition_matrix,emission_matrix,initial_probabilities)
print("\nBackward Matrix:\n",backward_matrix)
print("Probability of observation sequence:",prob_observation)

Enter the states(comma-separated): cp,ip
Enter the possible observations(comma-separated): lem,icet,cola
Enter the observation sequence as space_separated names(options:['lem', 'icet', 'cola']): lem icet cola



Enter the state transition probabilities:


P(cp|cp): 0.7
P(ip|cp): 0.5
P(cp|ip): 0.3
P(ip|ip): 0.5



Enter the emission probabilities:


P(lem|cp): 0.3
P(icet|cp): 0.1
P(cola|cp): 0.6
P(lem|ip): 0.2
P(icet|ip): 0.7
P(cola|ip): 0.1



Enter the initial state probabilities(comma-separated):


Enter initial probabilities for['cp', 'ip']: 1.0,0.0



Forward Matrix:
 [[0.3     0.021   0.02772]
 [0.      0.105   0.0063 ]]
Probability of observation sequence: 0.034019999999999995

Backward Matrix:
 [[0.1134 0.47   1.    ]
 [0.0946 0.23   1.    ]]
Probability of observation sequence: 0.03401999999999999
